<option>Bouenza (Madingou)</option>
<option>Brazzaville (Brazzaville)</option>
<option>Cuvette (Owando)</option>
<option>Cuvette-Ouest (Ewo)</option>
<option>Kouilou (Loango)</option>
<option>Lekoumou (Sibiti)</option>
<option>Likouala (Impfondo)</option>
<option>Niari (Dolisie)</option>
<option>Plateaux (Djambala)</option>
<option>Pointe-Noire (Pointe-Noire)</option>
<option>Pool (Kinkala)</option>
<option>Sangha (Ouesso)</option>