<option>Saint Andrew Parish</option>
<option>Saint David Parish</option>
<option>Saint George Parish</option>
<option>Saint John Parish</option>
<option>Saint Joseph Parish</option>
<option>Saint Luke Parish</option>
<option>Saint Mark Parish</option>
<option>Saint Patrick Parish</option>
<option>Saint Paul Parish</option>
<option>Saint Peter Parish</option>