<option>Estuaire (Libreville)</option>
<option>Haut-Ogooue (Franceville)</option>
<option>Moyen-Ogooue (Lambarene)</option>
<option>Ngounie (Mouila)</option>
<option>Nyanga (Tchibanga)</option>
<option>Ogooue-Ivindo (Makokou)</option>
<option>Ogooue-Lolo (Koulamoutou)</option>
<option>Ogooue-Maritime (Port-Gentil)</option>
<option>Woleu-Ntem (Oyem)</option>