<?php

$statearray = array(
    'Acklins',
    'Berry Islands',
    'Bimini',
    'Black Point, Exuma',
    'Cat Island',
    'Central Abaco',
    'Central Andros',
    'Central Eleuthera',
    'City of Freeport, Grand Bahama',
    'Crooked Island',
    'East Grand Bahama',
    'Exuma',
    'Grand Cay, Abaco',
    'Harbour Island, Eleuthera',
    'Hope Town, Abaco',
    'Inagua',
    'Long Island',
    'Mangrove Cay, Andros',
    'Mayaguana',
    'Moore's Island,
    Abaco',
'North Abaco',
'North Andros',
'North Eleuthera',
'Ragged Island',
'Rum Cay',
'San Salvador',
'South Abaco',
'South Andros',
'South Eleuthera',
'Spanish Wells,
    Eleuthera',
'West Grand Bahama',
'Green Turtle Cay',
'new Providence')?>

