<?php

$statearray = array(
    'Anse aux Pins',
    'Anse Boileau',
    'Anse Etoile',
    'Au Cap',
    'Anse Royale',
    'Baie Lazare',
    'Baie Sainte Anne',
    'Beau Vallon',
    'Bel Air',
    'Bel Ombre',
    'Cascade',
    'Glacis',
    'Grand'Anse','Grand'Anse Praslin',
    'La Digue and Inner Islands',
    'English River',
    'Mont Buxton',
    'Mont Fleuri',
    'Plaisance',
    'Pointe La Rue',
    'Port Glaud',
    'Saint Louis',
    'Takamaka',
    'Les Mamelles',
    'Roche Caiman',
    'Outer Islands (Zil Elwannyen Sesel)')?>
