<option>Ituau County</option>
<option>Ma'Oputasi County</option>
<option>Sa'Ole County</option>
<option>Sua County</option>
<option>Vaifanua County</option>
<option>Lealataua County</option>
<option>Leasina County</option>
<option>Tualatai County</option>
<option>Tualauta County</option>
<option>Faleasao County</option>
<option>Fitiuta County</option>
<option>Ofu County</option>
<option>Olosega County</option>
<option>Ta'u County</option>