<option>Lappi</option>
<option>Pohjois-Pohjanmaa</option>
<option>Kainuu</option>
<option>Pohjois-Karjala</option>
<option>Pohjois-Savo</option>
<option>Etela-Savo</option>
<option>Etela-Pohjanmaa</option>
<option>Keski-Pohjanmaa</option>
<option>Pohjanmaa</option>
<option>Pirkanmaa</option>
<option>Keski-Suomi</option>
<option>Satakunta</option>
<option>Varsinais-Suomi</option>
<option>Etela-Karjala</option>
<option>Paijat-Hame</option>
<option>Kanta-Hame</option>
<option>Uusimaa</option>
<option>Kymenlaakso</option>
<option>Ahvenanmaa</option>