<option>Christ Church</option>
<option>Saint Andrew</option>
<option>Saint George</option>
<option>Saint James</option>
<option>Saint John</option>
<option>Saint Joseph</option>
<option>Saint Lucy</option>
<option>Saint Michael</option>
<option>Saint Peter</option>
<option>Saint Philip</option>
<option>Saint Thomas</option>