<option>Dedza
<option>Dowa
<option>Kasungu
<option>Lilongwe
<option>Mchinji
<option>Nkhotakota
<option>Ntcheu
<option>Ntchisi
<option>Salima
<option>Chitipa
<option>Karonga
<option>Likoma
<option>Mzimba
<option>Nkhata Bay
<option>Rumphi
<option>Balaka
<option>Blantyre
<option>Chikwawa
<option>Chiradzulu
<option>Machinga
<option>Mangochi
<option>Mulanje
<option>Mwanza
<option>Nsanje
<option>Thyolo
<option>Phalombe
<option>Zomba
<option>Neno