<option>Anenii Noi</option>
<option>Basarabeasca</option>
<option>Briceni</option>
<option>Cahul</option>
<option>Cantemir</option>
<option>Calara?i</option>
<option>Cau?eni</option>
<option>Cimi?lia</option>
<option>Criuleni</option>
<option>Dondu?eni</option>
<option>Drochia</option>
<option>Dubasari</option>
<option>Edine?</option>
<option>Fale?ti</option>
<option>Flore?ti</option>
<option>Glodeni</option>
<option>HInce?ti</option>
<option>Ialoveni</option>
<option>Leova</option>
<option>Nisporeni</option>
<option>Ocni?a</option>
<option>Orhei</option>
<option>Rezina</option>
<option>RI?cani</option>
<option>SIngerei</option>
<option>Soroca</option>
<option>Stra?eni</option>
<option>?oldane?ti</option>
<option>?tefan Voda</option>
<option>Taraclia</option>
<option>Telene?ti</option>
<option>Ungheni</option>