<?php

$statearray = array(
    'Beijing Municipality',
    'Tianjin Municipality',
    'Hebei Province',
    'Shanxi Province',
    'Inner Mongolia Autonomous Region',
    'Nei Mongol Autonomous Region',
    'Liaoning Province',
    'Jilin Province',
    'Heilongjiang Province',
    'Shanghai Municipality',
    'Jiangsu Province',
    'Zhejiang Province',
    'Anhui Province',
    'Fujian Province',
    'Jiangxi Province',
    'Shandong Province',
    'Henan Province',
    'Hubei Province',
    'Hunan Province',
    'Guangdong Province',
    'Guangxi Zhuang Autonomous Region',
    'Hainan Province',
    'Chongqing Municipality',
    'Sichuan Province',
    'Guizhou Province',
    'Yunnan Province',
    'Tibet Autonomous Region',
    'Xizang Autonomous Region',
    'Shaanxi Province',
    'Gansu Province',
    'Qinghai Province',
    'Ningxia Hui Autonomous Region',
    'Xinjiang Uyghur Autonomous Region',
    'Hong Kong Special Administrative Region',
    'Xianggang Special Administrative Region',
    'Macau Special Administrative Region',
    'Aomen Special Administrative Region',
    'Taiwan Province')

?>
