<?php

$statearray = array(
    'Il-Kunsill Lokali tal-Belt Valletta',
    'Il-Kunsill Lokali tal-Imdina',
    'Il-Kunsill Lokali tal-Birgu',
    'Il-Kunsill Lokali tal-Isla',
    'Il-Kunsill Lokali ta'Bormla',
'Il - Kunsill Lokali ta' Hal Qormi',
    'Il-Kunsill Lokali ta'Haz - Zebbug',
'Il - Kunsill Lokali tas - Siggiewi',
'Il - Kunsill Lokali ta' Haz-Zabbar',
    'Il-Kunsill Lokali taz-Zejtun',
    'Il-Kunsill Lokali tar-Rabat, Ghawdex',
    'Il-Kunsill Lokali ta'H'Attard',
    'Il-Kunsill Lokali ta'Hal Balzan',
'Il - Kunsill Lokali ta' Birkirkara',
    'Il-Kunsill Lokali ta'Birzebbuga',
'Il - Kunsill Lokali ta' Had-Dingli',
    'Il-Kunsill Lokali tal-Fgura',
    'Il-Kunsill Lokali tal-Furjana',
    'Il-Kunsill Lokali tal-Fontana',
    'Il-Kunsill Lokali t'Ghajnsielem',
'Il - Kunsill Lokali tal - Gharb',
'Il - Kunsill Lokali ta' Hal Gharghur',
    'Il-Kunsill Lokali tal-Ghasri',
    'Il-Kunsill Lokali ta'Hal Ghaxaq',
'Il - Kunsill Lokali tal - Gudja',
'Il - Kunsill Lokali tal - Gzira',
'Il - Kunsill Lokali tal - Hamrun',
'Il - Kunsill Lokali tal - Iklin',
'Il - Kunsill Lokali tal - Kalkara',
'Il - Kunsill Lokali Ta' Kercem',
    'Il-Kunsill Lokali ta'Hal Kirkop',
'Il - Kunsill Lokali ta' Hal Lija',
    'Il-Kunsill Lokali ta'Hal Luqa',
'Il - Kunsill Lokali tal - Marsa',
'Il - Kunsill Lokali ta' Marsaskala',
    'Il-Kunsill Lokali ta'Marsaxlokk',
'Il - Kunsill Lokali tal - Mellieha',
'Il - Kunsill Lokali tal - Imgarr',
'Il - Kunsill Lokali tal - Mosta',
'Il - Kunsill Lokali tal - Imqabba',
'Il - Kunsill Lokali tal - Imsida',
'Il - Kunsill Lokali tal - Imtarfa',
'Il - Kunsill Lokali tal - Munxar',
'Il - Kunsill Lokali tan - Nadur',
'Il - Kunsill Lokali tan - Naxxar',
'Il - Kunsill Lokali ta' Rahal Gdid',
    'Il-Kunsill Lokali ta'Pembroke',
'Il - Kunsill Lokali Tal - Pieta',
'Il - Kunsill Lokali tal - Qala',
'Il - Kunsill Lokali tal - Qrendi',
'Il - Kunsill Lokali tar - Rabat',
'Il - Kunsill Lokali ta' Hal Safi',
    'Il-Kunsill Lokali ta'San Giljan',
'Il - Kunsill Lokali ta' San Gwann',
    'Il-Kunsill Lokali ta'San Lawrenz',
'Il - Kunsill Lokali ta' San Pawl il-Bahar',
    'Il-Kunsill Lokali Ta'Sannat',
'Il - Kunsill Lokali ta' Santa Lucija',
    'Il-Kunsill Lokali ta'Santa Venera',
'Il - Kunsill Lokali ta' Tas-Sliema',
    'Il-Kunsill Lokali tas-Swieqi',
    'Il-Kunsill Lokali ta'Hal Tarxien',
'Il - Kunsill Lokali ta' Ta'Xbiex',
'Il - Kunsill Lokali tax - Xaghra',
'Il - Kunsill Lokali tax - Xewkija',
'Il - Kunsill Lokali tax - Xghajra',
'Il - Kunsill Lokali taz - Zebbug,
    Ghawdex',
'Il - Kunsill Lokali taz - Zurrieq')?>

