<?php

$statearray = array(
    'Adygea',
    'Bashkortostan',
    'Buryatia',
    'Altai Republic',
    'Dagestan',
    'Ingushetia',
    'Kabardino-Balkar Republic',
    'Kalmykia, Republic of',
    'Karachay-Cherkess Republic',
    'Karelia',
    'Komi Republic',
    'Mari El Republic',
    'Mordovia',
    'Sakha (Yakutia) Republic',
    'North Ossetia-Alania',
    'Tatarstan',
    'Tuva Republic',
    'Udmurt Republic',
    'Khakassia',
    'Chechen Republic',
    'Chuvash Republic',
    'Altai Krai',
    'Zabaykalsky Krai',
    'Kamchatka Krai',
    'Krasnodar Krai',
    'Krasnoyarsk Krai',
    'Perm Krai',
    'Primorsky Krai',
    'Stavropol Krai',
    'Khabarovsk Krai',
    'Amur Oblast',
    'Arkhangelsk Oblast',
    'Astrakhan Oblast',
    'Belgorod Oblast',
    'Bryansk Oblast',
    'Vladimir Oblast',
    'Volgograd Oblast',
    'Vologda Oblast',
    'Voronezh Oblast',
    'Ivanovo Oblast',
    'Irkutsk Oblast',
    'Kaliningrad Oblast',
    'Kaluga Oblast',
    'Kemerovo Oblast',
    'Kirov Oblast',
    'Kostroma Oblast',
    'Kurgan Oblast',
    'Kursk Oblast',
    'Leningrad Oblast',
    'Lipetsk Oblast',
    'Magadan Oblast',
    'Moscow Oblast',
    'Murmansk Oblast',
    'Nizhny Novgorod Oblast',
    'Novgorod Oblast',
    'Novosibirsk Oblast',
    'Omsk Oblast',
    'Orenburg Oblast',
    'Oryol Oblast',
    'Penza Oblast',
    'Pskov Oblast',
    'Rostov Oblast',
    'Ryazan Oblast',
    'Samara Oblast',
    'Saratov Oblast',
    'Sakhalin Oblast',
    'Sverdlovsk Oblast',
    'Smolensk Oblast',
    'Tambov Oblast',
    'Tver Oblast',
    'Tomsk Oblast',
    'Tula Oblast',
    'Tyumen Oblast',
    'Ulyanovsk Oblast',
    'Chelyabinsk Oblast',
    'Yaroslavl Oblast',
    'Moscow',
    'Saint Petersburg',
    'Jewish Autonomous Oblast',
    'Nenets Autonomous Okrug',
    3Khanty–Mansi Autonomous Okrug – Yugra','Chukotka Autonomous Okrug','Yamalo -
        Nenets Autonomous Okrug')?>
