<?php

$statearray = array(
    'Almeria',
    'Cadiz',
    'Cordova',
    'Granada',
    'Huelva',
    'Jaen',
    'Malaga',
    'Seville',
    'Huesca',
    'Teruel',
    'Saragossa',
    'Asturias',
    'Balears',
    'alava-Araba',
    'Gipuzkoa',
    'Biscay',
    'Santa Cruz de Tenerife',
    'Las Palmas',
    'Cantabria',
    'Albacete',
    'Ciudad Real',
    'Cuenca',
    'Guadalajara',
    'Toledo',
    'avila',
    'Burgos',
    'Leon',
    'Palencia',
    'Salamanca',
    'Segovia',
    'Soria',
    'Valladolid',
    'Zamora',
    'Barcelona',
    'Girona',
    'Lleida',
    'Tarragona',
    'Badajoz',
    'Caceres',
    'Corunna',
    'Lugo',
    'Ourense',
    'Pontevedra',
    'La Rioja',
    'Madrid',
    'Murcia',
    'Navarre',
    'Alicante',
    'Castellon',
    'Valencia')?>
