<?php

$statearray = array(
    'Zurich',
    'Bern',
    'Lucerne',
    'Uri',
    'Schwyz',
    'Obwalden',
    'Nidwalden',
    'Glarus',
    'Zug',
    'Fribourg',
    'Solothurn',
    'Basel-Stadt',
    'Basel-Landschaft',
    'Schaffhausen',
    'Appenzell Ausserrhoden',
    'Appenzell Innerrhoden',
    'St. Gallen',
    'Graubunden',
    'Aargau',
    'Thurgau',
    'Ticino',
    'Vaud',
    'Valais',
    'Neuchatel',
    'Geneva',
    'Jura')?>
