<?php

$statearray = array(
    'Lviv',
    'Volyn',
    'Rivne',
    'Zakarpattia',
    'I.F',
    'Chernivtsi',
    'Ternopil',
    'Khmel',
    'Zhytomyr',
    'Vinnytsia',
    'Kiev',
    'Cherkasy',
    'Kirovohrad',
    'Mykolaiv',
    'Chernihiv',
    'Sumy',
    'Poltava',
    'Dnipropetrovsk',
    'Kharkiv',
    'Donetsk',
    'Kherson',
    'Zaporizhia',
    'A.R. Crimea',
    'Luhansk',
    'Dnieper',
    'Odessa')?>