<?php
$array = array("5TH Crescent",
"A. E. Akeinam street",
"Abdul Sallami",
"Abijan",
"Accra",
"Addis Ababa Crescent",
"Algeria",
"Algiers",
"Abali street",
"ASA",
"Balanga",
"Bengazi",
"Conakry",
"Constatine",
"Dalaba",
"Dan Suleiman",
"Daressalam Crescent",
"Doula Street",
"Embu Street",
"Ekukinam",
"Festus Okotie Ibo Street",
"Funmilayo Ransome Kutie",
"Gwani",
"Obafemi Awolowo",
"Oda Cresent",
"Oladipo Diya",
"Oro Ago crescent",
"Olusegun Obansanjo",
"Onitsha Crescent",
"Okonjo Iweala (Utako market)",
"I.V.W Osisiogu Street",
"IBN Haruna",
"Ibrahim Taiwo",
"Idimba",
"Jama'are Close",
"J.J Oluleye Street",
"Jimmy Carter Street",
"Julius Nyerere Crescent",
"Kitwe",
"Kumo Street",
"Kwame Nkuruma Street",
"Kigoma",
"Cap Town Street",
"Ladi Kwali",
"Lord Lugard Street",
"Maitama Sule",
"Michael Okpara",
"Mambolo",
"Maputo",
"Mombasa",
"Morovia Street",
"Nairobi Street",
"Nauakchatt",
"Nodola",
"Parakou Street",
"Sokode crescent",
"Suez Crescent",
"Shettima Mungolo",
"Thomas Sankara Street",
"Uke",
"Ubiaja",
"Udo Udoma",
"Uruguay Street",
"Usuman Street",
"Yakubu Gowon Crescent",
"Zambezi",
"Zigunchor Kitwe",
"Casandra Street",
"Salt Lake");

sort($array);

?>